// Generated by scripts/hero-still.mjs: do not edit by hand, re-run it.
// The stills of the 3D hall (public/hero).
//
// HALL_STILLS, the phone stills, and where the hall sits in each: a = the
// type's clearance line (the door rim's guard), b = the nearest plinths'
// feet, c = the Enter label, t and u = the door rim's top and bottom, as
// shares of the still's height; x = the hall's centre line as a share of its
// width; r = its height per px of the width the plinth files were fitted to.
// hero.css lays the still with them.
export const HALL_STILLS = {
  "phone": {
    "src": "/hero/hall-phone.webp",
    "avif": "/hero/hall-phone.avif",
    "width": 780,
    "height": 1688,
    "a": 0.3061,
    "b": 0.7994,
    "c": 0.4029,
    "t": 0.3094,
    "u": 0.4946,
    "x": 0.5,
    "r": 2.1641
  },
  "side": {
    "src": "/hero/hall-side.webp",
    "avif": "/hero/hall-side.avif",
    "width": 1688,
    "height": 780,
    "a": 0.2464,
    "b": 0.9487,
    "c": 0.4183,
    "t": 0.2522,
    "u": 0.588,
    "x": 0.734,
    "r": 0.8686
  }
} as const;

// STAGE_STILLS, one per aspect band (frame.ts STAGE_BANDS): the door rim's
// top and bottom as shares of the still's height. Hero.tsx lays the still
// with them (frame.ts layStill) so its door lands on the live scene's.
export const STAGE_STILLS = {
  "wide": {
    "src": "/hero/stage-wide.webp",
    "avif": "/hero/stage-wide.avif",
    "width": 1914,
    "height": 810,
    "rimTop": 0.2525,
    "rimBottom": 0.6437
  },
  "land": {
    "src": "/hero/stage-land.webp",
    "avif": "/hero/stage-land.avif",
    "width": 1909,
    "height": 1200,
    "rimTop": 0.3375,
    "rimBottom": 0.6416
  },
  "four": {
    "src": "/hero/stage-four.webp",
    "avif": "/hero/stage-four.avif",
    "width": 1524,
    "height": 1152,
    "rimTop": 0.3993,
    "rimBottom": 0.6759
  },
  "five": {
    "src": "/hero/stage-five.webp",
    "avif": "/hero/stage-five.avif",
    "width": 1526,
    "height": 1229,
    "rimTop": 0.4168,
    "rimBottom": 0.6856
  },
  "tall": {
    "src": "/hero/stage-tall.webp",
    "avif": "/hero/stage-tall.avif",
    "width": 1190,
    "height": 1250,
    "rimTop": 0.46,
    "rimBottom": 0.7147
  }
} as const;
