// Generated by scripts/hero-still.mjs: do not edit by hand, re-run it.
// The phone stills of the 3D hall (public/hero) and where the hall sits in
// each: a = the type's clearance line (the door rim's top), b = the nearest
// plinths' feet, c = the Enter slab, as shares of the still's height; x = the
// hall's centre line as a share of its width; r = its height per px of the
// width the plinth files were fitted to. hero.css lays the still with them.
export const HALL_STILLS = {
  "phone": {
    "src": "/hero/hall-phone.webp",
    "avif": "/hero/hall-phone.avif",
    "width": 780,
    "height": 1688,
    "a": 0.3061,
    "b": 0.7994,
    "c": 0.4029,
    "x": 0.5,
    "r": 2.1641
  },
  "side": {
    "src": "/hero/hall-side.webp",
    "avif": "/hero/hall-side.avif",
    "width": 1688,
    "height": 780,
    "a": 0.2464,
    "b": 0.9487,
    "c": 0.4183,
    "x": 0.734,
    "r": 0.8686
  }
} as const;
